### PR TITLE
Add hint to add babel-register prior to using it

### PR DESCRIPTION
**Pull request by sarupbanskota**

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Thanks for your PR. I rebased it to fix the build error. If the instructions you added work, we should add it to the `codemod -h` output too. In my experience, globally-installed packages aren't typically `require`able though right?

**Comment by sarupbanskota** [comment]
> In my experience, globally-installed packages aren't typically requireable though right? I get this when I try:

yeah you're prob right. 

Backstory:
I was coding a plugin within the babel repo, and the `--require babel-register` worked fine. When I recovered from laziness, I moved my plugin to its own repo hoping to release an npm package: https://github.com/sarupbanskota/babel-plugin-add-name-to-plugin. I got an error when I ran ` codemod --require babel-register ...`. I hastily assumed installing globally would fix it, so I sent a PR first and forgot about it, but when I did run it locally myself later, I ran into the same error.

However, I think we still need to do something here, because if you pull from my plugin repo, install `babel-register`(not globally) and try to run e.g `codemod --require babel-register --plugin src/ test/unnamed_plugins/babel-plugin-syntax-async-functions.js` you'll run into:

``` bash
~/babel-plugin-add-name-to-plugin/src/index.js:18
export default function ({ types: t }) {
^^^^^^
```

... which is not what we want. I haven't had a chance to dig in more in detail on how to resolve it, but maybe you'd have tips for me? (and I can update this PR accordingly with the appropriate thing once we have the right way)

thanks btw for the cool project!

**Comment by mcMickJuice** [comment]
@sarupbanskota if you run your `codemod` call as an npm script, does it work?

**Comment by sarupbanskota** [comment]
@mcMickJuice nope, same error :(

I did the following: 
1. `npm link babel-register` (without this it can't find `babel-register)
2. `codemod --require babel-register --plugin src/ test/unnamed_plugins/babel-plugin-syntax-async-functions.js` - same error I shared above about not recognising `export`
3. plugin a script called `codemod` within `package.json` scripts, followed by `npm run codemod`, same error as on 2

**Comment by mcMickJuice** [comment]
Do you have a .babelrc that has the appropriate plugins/presets to transpile your code?  babel-register looks for this file and appropriate plugins to modify your code.

**Comment by sarupbanskota** [comment]
@mcMickJuice That was it :-) 

I still feel we should make the following clearer. In my case I had to do:
1. `npm install babel-register --save-dev` && `npm install babel-preset-env`
2. `npm link babel-register`
3.  create a `.babel.rc` file with the following:

``` js
{
  "presets": ["env"]
}
```

I can update the PR to reflect this if y'all think it's a good idea :-)

**Comment by eventualbuddha** [comment]
It seems like that's too much to expect people to do. Maybe having an option that specifically tries to just make it work would be good? Something like `codemod --with-babel-plugin-loader --plugin ./path/to/es2017/plugin.js`. You could imagine a similar `codemod --with-typescript-plugin-loader …`.

**Comment by mcMickJuice** [comment]
so eschew babel-register in favor of directly referencing a babel plugin(s)?  Would it be out of the scope of this project to actually look for a .babelrc file and apply those presets/plugins if it exists?

My impression (and how I use babel-register with this library) is I have a separate project where I write my codemods.  I then am then modding files that are in an adjacent project.  My codemod script is run via npm scripts and all dependencies are installed locally and there are no globals.  Is the point of this PR/thread to include documentation around how to use babel-codemod in this way?

**Comment by eventualbuddha** [comment]
In my opinion, that's the right way to do this. Your codemods should be in a separate project from the code being modified. This `--require babel-register` thing is just a way to allow easier development testing of your codemods. If you already have your separate project for codemods, you can make babel-register a dependency and run `codemod` from that directory referencing the files to rewrite outside the project. 

However, a different setup – or a one-off codemod – makes this more annoying. What I was suggesting is having this project understand that you may want to load plugins written with future JS syntax and that it will just figure out how to make that happen, presumably using babel-register and babel-preset-env internally.

**Comment by mcMickJuice** [comment]
I think that'd work great.  So to clarify, in this situation the `codemod` command would be: 

* invoked globally 
* with a path to the codemod plugin and the path of files or directories to be modded
* with a switch to run files through babel plugin pipeline (babel-preset-env)

This feature would then be that switch, essentially and it wouldn't be necessary for users to have a project setup with those plugins installed and a .`babelrc` file defined (which, as you said, can be annoying for one off codemods)

Is that what you're after?

**Comment by eventualbuddha** [comment]
> Is that what you're after?

Yep! Sounds right to me. I'm not sure what the right way to do that is, but I'd love to hear suggestions.

**Comment by mcMickJuice** [comment]
Cool. Should we create a feature issue and move the discussion over there?

Sorry to hijack your PR thread @sarupbanskota :smiley

**Comment by eventualbuddha** [comment]
> Should we create a feature issue and move the discussion over there?

Yep, just created #29. I'll close this since there isn't really a clear way forward.

**Comment by sarupbanskota** [comment]
haha, no worries folks. thanks for taking this forward! i'll try to contribute code towards this if I can manage time this week and if isn't already taken care of!

**Comment by eventualbuddha** [comment]
Since #31 was just merged and babel-register is used internally, this issue is now moot. Hopefully you find it easier to develop codemods with auto transpilation of plugins!

**Pull request closed without merging**
